services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: web
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.f1f98309.rule=Host(`hms.beznet.org`)
      - traefik.http.routers.f1f98309.entrypoints=websecure
      - traefik.http.routers.f1f98309.tls.certResolver=letsencrypt
      - traefik.http.services.f1f98309.loadbalancer.server.port=8000

  db:
    image: mariadb:latest
    restart: unless-stopped
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_NAME:-hotel_app}
      MYSQL_USER: ${DB_USER:-dbuser}
      MYSQL_PASSWORD: ${DB_PASS:-dbpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-rootpassword}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dokploy-network

  dbdash:
    depends_on:
      - db
    image: adminer
    container_name: dbdash
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8000:8080"
    networks:
      - dokploy-network

# networks:
#   dokploy-network:
#     driver: bridge

networks:
  dokploy-network:
    external: true

volumes:
  mysql-data:
