services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: web
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - ci-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    restart: unless-stopped
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_NAME:-hotel_app}
      MYSQL_USER: ${DB_USER:-dbuser}
      MYSQL_PASSWORD: ${DB_PASS:-dbpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-rootpassword}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ci-network

  dbdash:
    depends_on:
      - db
    image: adminer
    container_name: dbdash
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8000:8080"
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge

volumes:
  mysql-data:
