services:
  web:
    container_name: hotel_app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=production
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-dbuser}
      - DB_PASS=${DB_PASS:-dbpass}
      - DB_NAME=${DB_NAME:-hotel_app}
    networks:
      - ci-network
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_DATABASE: ${DB_NAME:-hotel_app}
      MYSQL_USER: ${DB_USER:-dbuser}
      MYSQL_PASSWORD: ${DB_PASS:-dbpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-rootpassword}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ci-network

networks:
  ci-network:
    driver: bridge

volumes:
  mysql-data: