services:
  web:
    container_name: hotel_app
    image: ghcr.io/bezaleel22/hotel-hms:latest
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - dokploy-network
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    container_name: db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dokploy-network
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - dokploy-network
    restart: always
    depends_on:
      - db

networks:
  dokploy-network:
    driver: bridge

volumes:
  mysql-data: